name: Paper MC Server
version: 1.6.0
slug: paper-mc-server
description: Minecraft Paper server
url: https://github.com/uplandjacob/upland-ha-addons/tree/main/paper-mc-server
arch:
  - aarch64
  - amd64
init: false
image: ghcr.io/uplandjacob/upland-ha-addons-paper-mc-server-{arch}
hassio_api: true
startup: application
map:
  - config
options:
  eula: false

schema:
  eula: bool

ports:
  "6699/tcp": 25565
ports_description:
  "6699/tcp": "port for Minecraft"