build_from:
  armv7: ghcr.io/home-assistant/armv7-base-ubuntu:20.04
  aarch64: ghcr.io/home-assistant/aarch64-base-ubuntu:20.04
  amd64: ghcr.io/home-assistant/amd64-base-ubuntu:20.04
  i386: ghcr.io/home-assistant/i386-base-ubuntu:18.04
platform:
  armv7: arm/v7
  aarch64: aarch64
  amd64: amd64
  i386: i386