build_from:
  armv7: ghcr.io/uplandjacob/ha-base-debian-java-armv7:latest
  aarch64: ghcr.io/uplandjacob/ha-base-debian-java-aarch64:latest
  amd64: ghcr.io/uplandjacob/ha-base-debian-java-amd64:latest
  i386: ghcr.io/uplandjacob/ha-base-debian-java-i386:latest
