build_from:
  armv7: ghcr.io/uplandjacob/ha-base-debian-java-armv7:0.0.1
  aarch64: ghcr.io/uplandjacob/ha-base-debian-java-aarch64:0.0.1
  amd64: ghcr.io/uplandjacob/ha-base-debian-java-amd64:0.0.1
  i386: ghcr.io/uplandjacob/ha-base-debian-java-i386:0.0.1
platform:
  armv7: arm/v7
  aarch64: aarch64
  amd64: amd64
  i386: i386
